# Stage 1: Build Angular
FROM node:20-slim AS frontend-builder
WORKDIR /frontend
COPY UrbanCar_Front/package*.json ./
RUN npm install
COPY UrbanCar_Front/ .
RUN npm run build -- --configuration production

# Stage 2: Nginx con frontend + config para Container Apps
FROM nginx:alpine
COPY --from=frontend-builder /frontend/dist/urbancar-ec-frontend/browser /usr/share/nginx/html
COPY UrbanCar_Front/nginx/nginx.containerapp.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
