name: Build operaciones-service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "operaciones-service/**"
      - "proto/**"
      - ".github/workflows/operaciones-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push operaciones-service image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./operaciones-service/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/operaciones-service:latest