name: Build RentWheels Mobile Web

on:
  push:
    branches:
      - main
    paths:
      - "mobile/rentwheels_mobile/**"
      - ".github/workflows/rentwheels-mobile-web.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Flutter Web Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.2"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        working-directory: mobile/rentwheels_mobile
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: mobile/rentwheels_mobile
        run: flutter build web --release

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push RentWheels Mobile Web image
        uses: docker/build-push-action@v6
        with:
          context: ./mobile/rentwheels_mobile
          file: ./mobile/rentwheels_mobile/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/rentwheels-mobile-web:latest
